### ISSUE TITLE
Meta: Pathfora Roadmap

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#143]
# Roadmap

## High-level Goals

1. Make customization / branding far more simple for end users.
2. Integrate high value Lytics products.
3. Increase flexibility of existing Pathora features.
4. Expand event tracking to facilitate future highly targeted use cases.

## Tasks

Core task list will grow organically but all tasks should rollup into one of the key goals defined above. Ideally.

* [x] **Dynamic Content / Templaing**
	* **Overview**
	   * To take full advantage of the Lytics data object / present truly one-to-one experiences we need a more robust templating integration. Right now the modals are targeted based on audience but the content within is farily hard to customize based on the user. Lets explore integrating a pre-existing template parser and integrating that with the existing Lytics data object that is returned so we can add basic logic / dynamic values as part of a widget title or body.
	* **Tickets**
	   * https://github.com/lytics/pathforajs/issues/137
* [x] **Support "Exit Intent" as Display Condition**
	* **Overview**
	   * "Exit intent" is growing in popularity. To expand the flexibility of our widget targeting lets integrate a new "exitIntent" display condition that listens for a users mouse to exit the top of the browser window towards close or back. 
	* **Tickets**
	   * https://github.com/lytics/pathforajs/pull/141
* [x] **Content Recommendations**
	* **Overview**
	   * TBD	
	* **Tickets**
	   * TBD
* [ ] **Pre-made Theme Support**
	* **Overview**
	   * Its clear that customizing a Pathfora modal to match a brand is of high importance. This requires more than basic color changes, it requires style level changes. To help users explore the possibilities when it comes to CSS lets create and integrate a handful of themes based on feedback. Themes should each have their own CSS file that only gets loaded when necessary.
	* **Tickets**
	   * https://github.com/lytics/lio/issues/7985
* [ ] **Custom CSS Load**
	* **Overview**
	   * Along the same line of "themes" it is common for users to integrate their own CSS. On many occassions getting this CSS to serve properly (after the core css is loaded) has been a challenge, resulting in malformed modals due to overrides not registering. As a solution lets support adding the CSS file for an end user in the same way the core styles are added. For v1 lets just support the url for a css file as a part of the top level config, not on a widget by widget basis, that loads the contents of that url
	* **Tickets**
	   * TBD
* [x] **Form Progress Event(s)**
	* **Overview**
	   * In order to support a variety of use cases, both marketing and analytics, lets send an event when a form has been started and perhaps when CTAs or cancels have been hovered over (intent).
	* **Tickets**
	   * https://github.com/lytics/pathforajs/issues/144
* [x] Widget Overlap
	* **Overview**
	   * Since day once we've known that if two widgets are targeting the same user and loaded in the same physical position they will overlap. Though this can be fixed with proper targeting it puts the burdon on the end-user. We need to figure out a long term solution to this and then address it on both the Lytics campaigns side as well as the Pathfora side. Ideally there are no magical beans here and the "priority" or "rules" can be added to Pathfora.
	* **Tickets**
	   * https://github.com/lytics/pathforajs/issues/121
* [x] **Inline Widgets**
* [ ] **A/B Testing Enhancement**
* [ ] **Campaign / External ID Support**

**Comment by sarahyablok** [comment]
closing this, as I'll be adding a new roadmap ticket soon.
