### ISSUE TITLE
Event Callbacks

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#15]
### Objective
In order to make Pathfora more developer friendly when it comes to custom integrations we need to have more flexible callbacks for the various types of events the Pathfora widgets can trigger. This will allow a developer to handle journeys by creating cookies, passing data to alternate endpoints, etc.

### Scope
Implement ability to define callback function when Pathfora is initialized. Response should include at least two parameters: `type` and `payload` where type is a unique type for each of the types of event that can trigger the callback (e.g. click, loaded, form, etc.) and the payload contains data specific to that event as outlined below. This callback should be in addition to any native callback logic to provide events to lytics, google etc. 

### Tasks
* [x] Trigger Callback on Pathfora Load
* [x] Trigger Callback on Form Submission (form info / input values as payload)
* [x] Trigger Callback on Button Click (button info as payload)
* [x] Trigger Callback on Modal Open/Close (modal info / status as payload)

**Comment by dylo0** [comment]
@markhayden for callbacks on Form submission, button clicks and modal close there's already existing mechanics for callback functions. From examples/actionWidgets.html:
``` javascript
    var modal = pathfora.Message({
        id: 'test',
        layout: "modal",
        msg: "Welcome to our website",
        confirmAction: {
            name: "Test confirm action",
            callback: function() {alert("test confirmation")}
        },
        cancelAction: {
            name: "Widget cancelled",
            callback: function() {alert("Cancel button clicked")}
        }
    });
```

Confirm/cancel actions are fired when user clicked ok / cancel button,  'name' is used for jstag tag. 

Below I'm pasting tracking widgets function so you can see which actions are reported under which names to jstag.send(). Basicly we push basic widget data like id type etc, and for all widgets, this + action names for confirmations/ cancels, and form data on contact forms.

```javascript
        trackWidgetAction: function(action, widget, htmlElement) {
            var params = {
                'pf-widget-id': widget.id,
                'pf-widget-type': widget.type,
                'pf-widget-layout': widget.layout,
                'pf-widget-variant': widget.variant
            };

            switch (action) {
                case 'show':
                    pathforaDataObject.displayedWidgets.push(params);
                    break;
                case 'close':
                    pathforaDataObject.closedWidgets.push(params);
                    break;
                case 'confirm':
                    params['pf-widget-action'] = widget.confirmAction.name;
                    pathforaDataObject.completedActions.push(params);
                    break;
                case 'cancel':
                    params['pf-widget-action'] = widget.cancelAction.name;
                    pathforaDataObject.cancelledActions.push(params);
                    break;
                case 'submit':
                    var form = htmlElement;

                    params['pf-form-username'] = form.elements['username'].value;
                    params['pf-form-title'] = form.elements['title'].value;
                    params['pf-form-email'] = form.elements['email'].value;
                    params['pf-form-message'] = form.elements['message'].value;
                    break;
                case 'subscribe':
                    form = htmlElement;
                    params['pf-form-email'] = form.elements['email'].value;
            }

            params['pf-widget-event'] = action;
            api.reportData(params);
        },
```

Do you think it's sufficient in this points or you'd want to change something? Callbacks on Pathfora load and modal opens will need to be implemented.

**Comment by mjurczyk** [comment]
Hey guys, left you the issue up for a review, plus two things to discuss.

**Comment by araddon** [comment]
How do we get access to the global level actions (say we want to listen to any cancel/confirm/close/subscription) without having the list of messages similar to your tracking function above?   can you put that in the readme doc?

**Comment by mjurczyk** [comment]
@araddon hey :) ! did you mean global `callbacks` or `actions`? Callbacks are implemented in a different way, since they do not report anything via `jstag`, while actions do.
Also, global callbacks have not been implemented (right now events are widget-bound), I will take care of that. Could you please specify a sample use-case for them, so that I can get a feel of what exactly do we need and how I can create it properly (especially because global parameters are usually more harmful than useful)?

**Comment by markhayden** [comment]
hi @mjurczyk I belive we mean a callback on the action. So when a form is submitted, for instance, as a user I might want to perform more actions than just passing to Lytics via JStag. It is highly likely that I will want to trigger a content change, pass the submitted data to some other third party that isnt built into Pathfora, etc. 

So for a specific example: If I am using Keen.io (an analytics service) in addition to Lytics on my site. I'll need / want a way to define a js function as a callback to the submit action so I can properly track conversions across all my systems. 

Let me know if that makes sense or if we need better / more examples. Thanks!

**Comment by dylo0** [comment]
@markhayden I've merged callbacks into development branch. 
The example you provided currently can be achieved in two ways - by using callbacks and by using confirm/cancel actions like I described in my first comment here.

The difference between these two is following:
- actions are always reported using jstag into Lytics while callbacks are not.
- callbacks has payload param available, and it can be used within function.


@mjurczyk has described callbacks in readme under Event Callbacks section (it's on branch development now).

If you'd need to improve/change something or further explanation please let us know.
