### ISSUE TITLE
A/B Testing

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#16]
# Objective
Simple a/b testing is a requirement for many marketing efforts. The goal with this enhancement is to allow the developer to select from two pre-defined testing methods natively in Pathfora: 100, 50/50.

# Scope
In order to add basic ability to a/b test pathfora widgets a few things must happen. First, we will need to accept an additional parameter when configuring Pathfora allowing the user to define which a/b testing method to use. 

By default we will assume no a/b testing (100), which leaves us with one initial other type (50/50). Keep in mind that down the road we might need to implement 33,33,33 or 20,80 but not at this point in time.

In addition to setting this param we will need a way to associate one or more Pathfora widgets to this a/b testing scope. Initially only two will be allowed (50/50) but this might increase in the future. Determining which widget to show can be done by choosing a random number between 1 and 2 or 0 and 1 and executing the widget by array key. 

Finally, we must ensure we store the selected test method for each device and load from there for all future versions so that the experience is consistent. 

(see event tracking ticket for further details on reporting)

# Tasks
* [x] Configure A/B Test Param
* [x] Associate Multiple Widgets by Test
* [x] Store Selected Test Version as Cookie
* [x] Prioritize Cookied Test Version if Exists

**Comment by mjurczyk** [comment]
@markhayden please see https://github.com/lytics/pathforajs/blob/feature/16-ab-testing/AB_TESTING.md for more information about the feature, and please let me know if that's the implementation you requested.

Also, feature scales for future testing modes (33/33/33, 80/20 etc.), currently implements only 100 and 50/50.
