### ISSUE TITLE
Content Gating Widget

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#22]
### Objective
Create a new type of widget used to gate content or a page. Once data has been collected, generally contact info, the gate should be hidden and access to content allowed. 

### Scope
Version 1 of content gating should be triggered by one of two events.   

Current would hide the content of the current page until the form has been submitted successfully. This modal would be triggered as soon as the page began to load.

New would generally be used for PDF downloads or some other type of downloadable content. This would be triggered from a button, upon completion of the form the end url would then be loaded (e.g. the download).

Regardless of the type of action the core function would be a simple contact form as described in attached images below.

Also pictured is the integrated functionality with social sign in as addressed in ticket #23 22. Based on the config a user should be able to determine which types of data collection they allow (standard form, facebook, google).   

Gating with standard form only:
![ss-3](https://cloud.githubusercontent.com/assets/2042008/12103381/2977c528-b2ff-11e5-8e50-e814def5d8ad.png)

Gating with multiple options available:
![ss-2](https://cloud.githubusercontent.com/assets/2042008/12103383/3116f588-b2ff-11e5-9b0a-ba30ec2d34b5.png)

Gating with social sign in only:
![ss-1](https://cloud.githubusercontent.com/assets/2042008/12103384/3345188a-b2ff-11e5-8601-e776f88b0685.png)

Somehow we need to ensure that for that particular gate, if info has been sent successfully it should not be triggered on future visits. Possibly use local storage or a cookie here. This prevents me from filling out the form and then coming back later to view content only to have to submit the same form again.

Data should be passed directly to Lytics as well as be available for further processing via callbacks.

### Tasks
* [x] Add new modal type and set up proper triggers.
* [x] New gating functionality. Submission status stored as cookie or local storage.
* [x] Add social sign in to existing modal (after social sign in has been completed)
