### ISSUE TITLE
Social Login (Facebook & Google)

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#23]
### Objective
Social sign in simplifies the amount of data a user has to enter to fulfill forms, content gating, etc. We would like all widgets to support this type of one click data collection in addition to standard email / name fields as they exist today. For the initial launch we will focus on Facebook and Google while in a later version we will explore LinkedIn and possibly Twitter.

### Scope
**Facebook**
Add social sign in integration for Facebook. Button click should trigger an auth window in which we ask for `public_profile` and `email` as the scope of the auth. From this we should be able to get name, email and a handful of other public data that should be passed to Lytics / as a payload in the callback. 

https://developers.facebook.com/docs/facebook-login/web/login-button

**Google**
Google will function nearly exactly to the Facebook integration above, the only difference is the scope we will be seeking is `profile`. This agin should allow for basic contact information to be collected / passed as opposed to a full manual form for the end user. 

https://developers.google.com/identity/sign-in/web/sign-in

Examples of what these buttons will look like an how they might be used in execution can be found: https://github.com/lytics/pathforajs/issues/22

Once the inital support is in place and tested we can create additional tickets to roll the actual buttons out to all of the modal types, initially we will focus on the gate as referenced above.

### Tasks
* [x] Facebook social sign in integration.
* [x] Google social sign in integration.
* [x] Finalize data passed as payload (can review after we have a better idea of exact data we can get from the api)
